### ISSUE TITLE
Git install isn't working in ubuntu

### ISSUE THREAD

**Issue by tanayz** [blatinier/pyhunspell#10]
This particular package can't be installed via git in ubuntu.Here is the code
[uszllmd]:~/src$ git clone https://github.com/blatinier/pyhunspell.git
Cloning into 'pyhunspell'...
remote: Counting objects: 109, done.
remote: Total 109 (delta 0), reused 0 (delta 0), pack-reused 109
Receiving objects: 100% (109/109), 43.96 KiB | 0 bytes/s, done.
Resolving deltas: 100% (57/57), done.
Checking connectivity... done.
[uszllmd]:~/src$ cd pyhunspell/
[uszllmd]:~/src/pyhunspell$ python setup.py install
/home/uszllmd/anaconda/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'compile_args', 'macros'
  warnings.warn(msg)
running install
running build
running build_ext
building 'hunspell' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I['/usr/include/hunspell'] -I/home/uszllmd/anaconda/include/python2.7 -c hunspell.c -o build/temp.linux-x86_64-2.7/hunspell.o
hunspell.c:21:22: fatal error: hunspell.h: No such file or directory
 #include <hunspell.h>
                      ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by blatinier** [comment]
You are missing the libhunspell-dev package in your distrib. Since this package is a python binding, it needs to compile using the headers of the hunspell C program (that's why you get: "hunspell.h: No such file or directory").

pip nor the package is in charge to install the underlying program.

I quote the README:
"Make sure that python-dev and libhunspell-dev are installed."

**Comment by tanayz** [comment]
Blatnier,

Thanks,it got installed now successfully after resolving the dependency.However can you tell me whether these following dictionaries come pre-loaded with it or I've to download it from some place.

hobj = hunspell.HunSpell('/usr/share/myspell/en_US.dic', '/usr/share/myspell/en_US.aff')

**Comment by blatinier** [comment]
The english dictionnaries are preinstalled if I remember well.
However for other dictionnaries you will have to install them though your system package manager.
If you don't have en dictionnaries install the following package: hunspell-en (apt-get install hunspell-en)
Usually the package name is like that : hunspell-{LANG-CODE}
To search for it in Ubuntu/Debian: apt-cache search hunspell.

For example in ArchLinux gives me the following available packages:
    extra/hunspell-de 20131206-1
        German hunspell dictionaries
    extra/hunspell-en 2015.05.18-4
        English hunspell dictionaries
    extra/hunspell-es 1:0.8-1
        Spanish hunspell dictionaries
    extra/hunspell-fr 5.3-1 [installé]
        French (modern) hunspell dictionaries
    extra/hunspell-he 1.2-2
        Hebrew hunspell dictionary
    extra/hunspell-it 2.4-4
        Italian dictionary for Hunspell
    extra/hunspell-ro 3.3.8-1
        Romanian dictionary for Hunspell
    community/hunspell-el 0.9-2
        Greek hunspell dictionary
    community/hunspell-hu 1.6.1-3
        Hungarian hunspell dictionary
    community/hunspell-nl 2.10g-2
        Dutch hunspell dictionaries
    community/hunspell-pl 20150428-2
        Polish dictionary for Hunspell

**Comment by tanayz** [comment]
Thanks Blatinier!
I got them from here
https://github.com/mercutiodesign/texmaker-3.3.3/tree/master/dictionaries

**Comment by blatinier** [comment]
It's another way of getting those :)
