### ISSUE TITLE
pip install isn't working in ubuntu/windows

### ISSUE THREAD

**Issue by tanayz** [blatinier/pyhunspell#11]
> pip install pyhunspell
Collecting pyhunspell
  Could not find a version that satisfies the requirement pyhunspell (from versions: )
No matching distribution found for pyhunspell

**Comment by blatinier** [comment]
Package name in pypi is "hunspell".
https://pypi.python.org/pypi/hunspell

**Comment by tanayz** [comment]
Even the new name isn't working in ubuntu/windows

[uszllmd]:~/src/pyhunspell$ pip install hunspell
Collecting hunspell
  Using cached hunspell-0.3.3.tar.gz
Installing collected packages: hunspell
  Running setup.py install for hunspell
    Complete output from command /home/uszllmd/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-sgP7K1/hunspell/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cqduzm-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'hunspell' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_LINUX -I/usr/include/hunspell -I/home/uszllmd/anaconda/include/python2.7 -c hunspell.c -o build/temp.linux-x86_64-2.7/hunspell.o -Wall
    hunspell.c:21:22: fatal error: hunspell.h: No such file or directory
     #include <hunspell.h>
                          ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/uszllmd/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-sgP7K1/hunspell/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cqduzm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-sgP7K1/hunspell

**Comment by blatinier** [comment]
See my comment on your other issue.
