### ISSUE TITLE
infringed become fringe

### ISSUE THREAD

**Issue by coiby** [blatinier/pyhunspell#14]
Hi,

I've been using pyhunspell for several days. It turns out to be quite a good stemmer. But it failed to stem the word `infringed` correctly today:
```python
import hunspell
hobj = hunspell.HunSpell('/usr/share/hunspell/en_US.dic', '/usr/share/hunspell/en_US.aff')
print hobj.stem('infringed')
```
It returns `fringe` instead of `infringe`. 

Why does this happen? How can it be fixed? 

Thank you!

**Comment by blatinier** [comment]
This is more an hunspell bug than a py-hunspell bug.

Here a test without using the python binding:

    $ hunspell -d en_US -s             
    infringed   # this is my input
    infringed fringe  # this is the response, composed like this: "input" "result"

The response may have multiple lines if multiple stems are available.
You can report a bug here: https://github.com/hunspell/hunspell/issues/p/hunspell/bugs/

**Comment by PanderMusubi** [comment]
Or report here http://wordlist.aspell.net/
