### ISSUE TITLE
`hunspell.error` not found

### ISSUE THREAD

**Issue by lastorset** [blatinier/pyhunspell#21]
I'm not sure how to catch exceptions when instantiating HunSpell:

```python
import hunspell
try:
    hunspell.HunSpell('non-existent.dic', 'also not found.aff')
except ???:  # Which exception do I catch here?
    pass
```

Trying a bare `except` clause containing `sys.exc_info()`, I find a `hunspell.error`. While `hunspell.error` is defined and can be retrieved this way, I think it's missing from the module dictionary:

```
In [13]: hunspell.hunspell.error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-eae33c488a03> in <module>()
----> 1 hunspell.hunspell.error

AttributeError: 'module' object has no attribute 'hunspell'
```

Perhaps the initialization procedure is missing this?

```c
PyModule_AddObject(mod, "error", HunSpellError);
```

**Comment by blatinier** [comment]
Thanks for the report.

You can now catch the error. It's named HunSpellError in the hunspell module.
