### ISSUE TITLE
hunspell.h is missing

### ISSUE THREAD

**Issue by PriyamBakliwal** [blatinier/pyhunspell#23]
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/hunspell -I/usr/include/python2.7 -c hunspell.c -o build/temp.linux-x86_64-2.7/hunspell.o
hunspell.c:21:22: fatal error: hunspell.h: No such file or directory
 #include <hunspell.h>
                      ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by blatinier** [comment]
See in the read me:

> Make sure that python-dev and libhunspell-dev are installed.

Did you installed that before doing pip install ?

**Comment by PriyamBakliwal** [comment]
Yes the problem is solved.
My bad, I didnt look at the previous issues
Thanks.

**Comment by blatinier** [comment]
No problem, hap'pyhunspell :)
