### ISSUE TITLE
'suggest' Returning bytestring on Python 3.4.3

### ISSUE THREAD

**Issue by orotau** [blatinier/pyhunspell#24]
When I run say
`hobj.suggest('haukāinga')`

This is the return I get
`[b'hau k\xc4\x81inga', b'haukotinga', b'haukoringa', b'haunuinga']`

As a workaround I do
`[x.decode() for x in hobj.suggest('haukāinga')]`

which gives me the more readable
`['hau kāinga', 'haukotinga', 'haukoringa', 'haunuinga']`

Not a major problem but thought you may like to know
Thanks for the very useful program

**Comment by xen** [comment]
I'm also found this little annoying.

**Comment by blatinier** [comment]
This is now implemented in pyhunspell 0.5.0.

**Comment by orotau** [comment]
Thanks for fixing this. I came across it today and tidied up my code accordingly.
