### ISSUE TITLE
Setting up pyhunspell on windows 10

### ISSUE THREAD

**Issue by jaideeppatel** [blatinier/pyhunspell#29]
Hi blatiner/others,

I see from your documentation that we need to install python-dev and hunspell-dev before running the command:
pip install hunspell 

But I am facing challenges installing the hunspell-dev on my windows environment. 
Any detailed steps or useful links to install python-dev and hunspell-dev would be highly useful.
Also, does python-dev mean python or is it something else?
Currently, I am using anaconda and pycharm.

Regards,
Jaideep

**Comment by blatinier** [comment]
Hi,

First, python-dev is a linux package which includes python header files (.h files) needed to compile python packages (such as this one) which are not distributed as binaries and are not pure python.

On windows however I don't know how all of this works unfortunatly...
According to this [stackoverflow](https://stackoverflow.com/a/24163212/1450754) answer, the "python-dev" part is installed by default on windows, but it doesn't solve the hunspell-dev part...
A contributor made a windows binary which I host here https://pyhunspell.latinier.fr/. 
It works for python 3.4 on windows7 (at least he compiled it for that :) ). 
This binary is not the latest version of the package (0.3.3 while the latest is 0.4.1). You will only miss the generate2 method, other than that it's mostly documentation fixes.

If by any chance you're making the pre-compiled package work on your station, I'm interested in knowing your windows & python version. 
And if you compile the lastest version, I'd be happy to check and host it too for future users.
And if you happen to find how to do the whole compilation thing, I'd appriciate very much you comming back here and explain so I can add it in the documentation (and you as a contributor of course).

Sorry I'm not of a great help here...
Others?

**Comment by jaideeppatel** [comment]
Hi blatiner,

Thanks for your response. I tried compiling the library on windows but ran into some issues. 
I tried it on Linux and it worked great. Below are the steps that I followed to get it running on Linux and python:
Install the latest release from the below link: 
https://github.com/hunspell/hunspell/releases

Install packages: autoconf automake autopoint libtool g++
Command: sudo apt-get install package-name

Run below commands:
autoreconf -vfi 
./configure 
make 
make install

setup environments: 
Run commands: (sudo apt-get install package-name)
python-dev 
libhunspell-dev

If you are using anaconda for python then run the following commands:
$ conda install libgcc (to update conda's c++ library)
(Note: https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error)

On the python environment:
import hunspell
This should set up all you need and you should be able to use Hunspell on python.

Hopefully, if I find some time I will give another shot on trying to run on windows. Will post an update if it works for me.

Thanks.

**Comment by blatinier** [comment]
Thanks for your feedback. If you succeed on Windows please open a new issue to update documentation. Or do a PR as you prefer.

I close this one.

**Comment by LazyPolyLing** [comment]
https://pyhunspell.latinier.fr/ website is not available anymore. Does this mean hunspell simply cannot be used on windows?

**Comment by RishabhMech** [comment]
Hi Jaydeep, did you come to know how that thing works on windows, yet?
