### ISSUE TITLE
Problem with pip install on Python 3 / Sierra

### ISSUE THREAD

**Issue by bittlingmayer** [blatinier/pyhunspell#31]
`pip install hunspell` yields the following error on python 3.5.1 (macOS Sierra):

> fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /var/folders/x2/10f_q7xx4bb2cqz8qldp2pnc0000gn/T//ccTftJQi.out

Apparently would not happen in Python 2, see https://stackoverflow.com/questions/6839795/cant-figure-out-the-architecture-type-of-problem-when-compiling-python

**Comment by bittlingmayer** [comment]
Fixed with `brew unlink apple-gcc42`

See https://github.com/regebro/hovercraft/issues/80

**Comment by blatinier** [comment]
I added some information about that in the readme. Thanks for the help 👍
