### ISSUE TITLE
Trouble in linking Hunspell to python

### ISSUE THREAD

**Issue by bmkor** [blatinier/pyhunspell#38]
Hi guys. I did install hunspell successfully on my Mac 10.12.6 via brew and have been able to execute hunspell under terminal. 

However, when I link the hunspell to my python (v3.6.4) via pip, I got the following error message after executing` import hunspell`:

> import hunspell
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
> ImportError: dlopen(/Users/usr/miniconda3/envs/nlp/lib/python3.6/site-> packages/hunspell.cpython-36m-darwin.so, 2): Symbol not found: > __ZN8Hunspell14add_with_affixERKSsS1_
>  Referenced from: /Users/usr/miniconda3/envs/nlp/lib/python3.6/site-packages/hunspell.cpython-> 36m-darwin.so
>  Expected in: flat namespace
>  in /Users/usr/miniconda3/envs/nlp/lib/python3.6/site-packages/hunspell.cpython-36m-darwin.so

Would anyone please help? Thanks a lot!

**Comment by blatinier** [comment]
You can try what people tried in #33 it's the same problem (still unsolved).
If you feel up to it you can dig into it!

**Comment by blatinier** [comment]
I close because it's duplicated
