### ISSUE TITLE
Get list of words

### ISSUE THREAD

**Issue by rominf** [blatinier/pyhunspell#52]
I want to get the list (or generator) of all words in the dictionary to perform some statistical data extraction. To be more specific, I want to calculate for all characters from the alphabet maximum count of consecutive characters in dictionary word.

**Comment by PanderMusubi** [comment]
Then you are much better off using the word list packages of Ubuntu or Debian. The package names are:

    wamerican
    wbrazilian
    wbritish
    wbulgarian
    wcanadian
    wcatalan
    wdanish
    wdutch
    wesperanto
    wfaroese
    wfrench
    wgaelic
    wgalician-minimos
    wirish
    witalian
    wmanx
    wngerman
    wnorwegian
    wpolish
    wportuguese
    wspanish
    wswedish
    wswiss
    wukrainian

These can also be downloaded and extracted on other operating systems.

Reconstructing word lists from .aff and .dic files is not trivial anymore.

**Comment by rominf** [comment]
@PanderMusubi, OK got it. Thank you!

**Comment by PanderMusubi** [comment]
If you are missing certain word lists, please contact the maintainers of the related packages for Hunspell or MySpell and ask them to release also a word list package for that language.

**Comment by blatinier** [comment]
Thanks for the support @PanderMusubi
