### ISSUE TITLE
MacOS Mojave install failure  '-std=libc++'

### ISSUE THREAD

**Issue by sriki77** [blatinier/pyhunspell#55]
```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -D_LINUX -I/usr/local/Cellar/hunspell/1.6.2/include/hunspell -I/anaconda3/include/python3.6m -c hunspell.cpp -o build/temp.macosx-10.7-x86_64-3.6/hunspell.o -Wal
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++
      standard library instead [-Wstdlibcxx-not-found]
In file included from hunspell.cpp:20:
In file included from /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:74:
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/w_char.hxx:41:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```
Installation is failing due the the above error. Please provide suggestions.

**Comment by blatinier** [comment]
That seems more like missing the basics about compiling stuff on your mac. 

    include path for stdlibc++

You should install the needed stuff to compile c++. I don't know the MacOS universe but from what I have read out there, you can install XCode which will install the needed pacakges. Or you can try and type "g++" in a term, which might trigger an installation process.

**Comment by sriki77** [comment]
I fixed the issue, the issue is with latest OSX Mojave. I had to install g++8.2 separately. Running the installer by changing the C++ compiler should work; meaning with option:
` CC=/usr/local/gcc-8.2/bin/gcc-8.2`

Please close the issue. Thank you for responding.

**Comment by charan1994** [comment]
There is an alternative to installing g++ separately and then running it as well. Just use 
`export MACOSX_DEPLOYMENT_TARGET=10.9`
and then run 
`CFLAGS=$(pkg-config --cflags hunspell) LDFLAGS=$(pkg-config --libs hunspell) pip install hunspell`
