### ISSUE TITLE
Update urls in documentation

### ISSUE THREAD

**Issue by PanderMusubi** [blatinier/pyhunspell#7]
Please update all urls in documentation, in packages and websites.

https://pypi.python.org/pypi/hunspell still refers to https://code.google.com/p/pyhunspell/wiki/UsingPyHunspell

the debian/ubuntu package regers to https://code.google.com/p/pyhunspell/

Additional question, is debian/ubuntu already shipping code from this project? See also https://bugs.launchpad.net/ubuntu/+source/pyhunspell/+bug/1326518

**Comment by blatinier** [comment]
I updated the README in pypi to remove references to code.google.com.

Concerning Debian/Ubuntu they seems to ship a really old version of the package (0.1) but I don't really know the process of Debian/Ubuntu team to upgrade packages, who should I contact etc…
If you are more knowledgeable than me on that please enlighten me :)

**Comment by PanderMusubi** [comment]
I have send you a message with email addresses you can contact for upgrading the Debian/Ubuntu package.

**Comment by marios-zindilis** [comment]
You could also update the description of this very repository.

**Comment by blatinier** [comment]
@marios-zindilis  Done

**Comment by blatinier** [comment]
The debian maintainer of this package contacted me and the version is now up to date. I don't know if it's in testing or unstable, but at least it's in the debian releasing pipe.
