### ISSUE TITLE
Availability of binaries for Win7

### ISSUE THREAD

**Issue by tallforasmurf** [blatinier/pyhunspell#9]
I have made available binaries of pyhunspell for Windows 7 AMD-64 and Windows 7 32-bit at the following url:

    https://www.dropbox.com/sh/wbu6yzj3x0hypyh/AACO6Pjb-_8VyWEbDfJ66SgPa?dl=0

I will leave them in my Public Dropbox for a while, a few months anyway. Or, if the maintainer wants to copy them or replace them with his own on this site, fine.

**Comment by 5j9** [comment]
"The file you’re looking for has been moved or deleted."

**Comment by tallforasmurf** [comment]
Well, like I said, "a few months". When I have time I will look for them and maybe put them back up.

In the meantime you might ask the owner of the repo.

**Comment by tallforasmurf** [comment]
https://www.dropbox.com/sh/tywa20glg8dcvv3/AACfOAoaTD2g51lI4LHGNU-Ga?dl=0

These were compiled for Python 3.4. Hopefully they will work also with 3.5. No guarantees, no promises.

**Comment by 5j9** [comment]
Helped a lot. Thank you, tallforasmurf!

**Comment by blatinier** [comment]
I put the binaries on a personal server which won't delete the file and linked it in the README.md (with credits to @tallforasmurf since he did the job)
